/**
 * The shape of `public/cards.json`.
 *
 * Generated by `pnpm build:cards` from every `*.spec.md` under
 * `corpus/nz-election-2026/`. This file is
 * the contract between that generator and the app: the canvas, the card and the
 * game all import from here and none of them parse Gurki.
 *
 * One card per policy, with two faces. `stated` is the party's claim.
 * `derived` is our understanding of the same policy, and is absent when nobody
 * wrote one. The UI toggles between them; it must never blend them.
 *
 * Owned by the dataset generator. If the app needs a field that is not here,
 * the generator changes first.
 */

export type PartyId =
  | 'act'
  | 'green'
  | 'labour'
  | 'national'
  | 'nz-first'
  | 'opportunity'
  | 'te-pati-maori'

export type StepKind =
  | 'given'
  | 'when'
  | 'then'
  | 'output'
  | 'outcome'
  | 'activates'

export type Connector = 'and' | 'but' | null

export type MoneyClass = 'named-figure' | 'no-figure'

export type CardFaceKind = 'stated' | 'derived'

export type CardStep = {
  kind: StepKind
  connector: Connector
  /** The Gurki keyword to print: "Given", "And", "But". */
  surface: string
  text: string
  /**
   * True when the step's figure is arithmetic from the page rather than printed
   * on it. Only ever true on a derived face.
   */
  extrapolated: boolean
  /** Why, when `extrapolated`. */
  reason?: string
}

export type CardScenario = {
  title: string
  steps: CardStep[]
}

/** A derived System Outputs / System Outcomes line. */
export type ReportItem = {
  text: string
  connector: Connector
}

export type CardFace = {
  kind: CardFaceKind
  /** The spec this face was generated from. */
  specId: string
  title: string
  summary?: string
  system?: string
  /** The spec's opening note. Stated: a neutral party overview. Derived: our understanding. */
  note?: string
  scenarios: CardScenario[]
  report: { outputs: ReportItem[]; outcomes: ReportItem[] }
  /** Card ids this face points at. Unresolved targets are dropped. */
  activates: string[]
  counts: {
    scenarios: number
    steps: number
    outputs: number
    outcomes: number
    extrapolated: number
  }
}

export type PolicyCard = {
  /** The stated spec's id. One card is one policy page. */
  id: string
  party: PartyId
  title: string
  summary?: string
  clusters: string[]
  tags: string[]
  money: MoneyClass
  source: { title: string; url: string; path: string }
  /** What the policy does not answer. From the stated spec. */
  gaps: string[]
  /** Reasoning we supplied. From the derived spec; empty when there is none. */
  assumptions: string[]
  stated: CardFace
  derived?: CardFace
  counts: { gaps: number; assumptions: number }
}

export type ClusterMeta = {
  id: string
  label: string
  description: string
}

export type PartyMeta = {
  id: PartyId
  label: string
  name: string
  colour: string
  cardCount: number
}

/** Cards per party per cluster. The game's eligibility rule reads this. */
export type CoverageCell = {
  cluster: string
  party: PartyId
  cards: number
}

export type CardsDataset = {
  schemaVersion: '2'
  generatedAt: string
  clusters: ClusterMeta[]
  parties: PartyMeta[]
  coverage: CoverageCell[]
  cards: PolicyCard[]
}
